[devshell]
packages = [
  "alejandra", # Formatter for nix
  "dprint", # Formatter for misc
  "poetry", # Python package manager
  "black", # Formatter for Python
]

[[commands]]
package = "treefmt"
category = "formatter"
